server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/promatail-positions.yaml
clients:
  - url: 'http://localhost:3100/loki/api/v1/push'
scrape_configs:
  - job_name: json
    pipeline_stages:
      - json:
          expressions:
            timestamp: '"@timestamp"'
            level: level
            logger: logger
            marker: marker
            thread: thread
            service: service
            session: session
            pid: pid
            server_ip: '"server-ip"'
            server_host: '"server-host"'
            client_ip: '"client-ip"'
            client-host: '"client-host"'
            request_url: requestURL
            referer: referer
            status_code: '"status-code"'
            elapsed_time: elapsedTime
            class_method: '"class-method"'
            line: line
            dd_trace_id: '"dd-trace-id"'
            dd_span_id: '"dd-span-id"'
            trace_id: '"trace-id"'
            span_id: '"span-id"'
            message: message
            exception: exception
      - labels:
          timestamp:
          level:
          logger:
          marker:
          thread:
          service:
          request_url:
          status_code:
          elapsed_time:
          dd_trace_id:
          dd_span_id:
          trace_id:
          span_id:
          server_ip:
          client_ip:
          class_method:
          line:    
      - drop:
          source: "level"
          value:  "TRACE"
      - drop:
          source: "level"
          value:  "DEBUG"
      - drop:
          source: "level"
          value:  "INFO"
      # - drop:
      #     source: "level"
      #     value:  "WARN"
      # - drop:
      #     source: "level"
      #     value:  "ERROR"
      # - drop:
      #     source: "level"
      #     value:  "FATAL"
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /Users/codebit/Workspaces2/cp/cp-gateway/logs/app-json*.log
          # __path__: /var/logs/application/app-json*.log
          __path_exclude__:
